[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E1", "E4", "E7", "E9", "F", "B", "F841","F901", 'N', 'D419', 'D418', 'D103', 'D102', 'D101', 'UP031', 'UP032', 'S102','S608','S611']

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501", 'N807']

[lint.per-file-ignores]
"*/migrations/*.py" = ["D"]
"*/{apps,admin}.py" = ["D", "F"]

[format]
quote-style = "double"
indent-style = "tab"