name: Python checks

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install mypy
    - name: Analysing the code with Ruff
      run: |
        ruff check $(git ls-files '*.py')
    - name: Analysing the Python typing with MyPy
      run: |
        mypy $(git ls-files '*.py')
